baseURL = 'https://olafradicke.github.io/robert_barclay_apologie_1776/'
languageCode = 'de-de'
title = 'Apologie von Robert Barclay in der Übersetzung von 1776'

DefaultContentLanguage = "de"
# site_logo = '/images/Mastodon_logo.svg'
theme = "ace-documentation"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "de"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
enableRobotsTXT = true

[params]
ordersectionsby = "weight" # ordersectionsby = "title"
disableSearch = false # default is false
disableReadmoreNav = false # set true to hide prev/next navigation, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
custom_css = ["css/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = 'Schlagworte'
  category = 'Bearbeitungsstand'

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
name = "Zum Git-Repo"
url = "https://github.com/OlafRadicke/robert_barclay_apologie_1776"
weight = 1
