#baseURL = "https://olafradicke.github.io/robert_barclay_apologie_1776/"
baseURL = "https://apologie.the-independent-friend.de"

languageCode = "de-de"
DefaultContentLanguage = "de"
title = "Apologie  von Robert Barclay in der Übersetzung von 1776"
theme = "hugo-theme-techdoc"

name = "Apologie  von Robert Barclay in der Übersetzung von 1776"
license = "Creative Commons Legal Code"
licenselink = "https://github.com/OlafRadicke/robert_barclay_apologie_1776/blob/add-hugo/LICENSE"
description = "Apologie von Robert Barclay in der Übersetzung von 1776"
homepage = "https://github.com/OlafRadicke/robert_barclay_apologie_1776"
repo = "https://github.com/OlafRadicke/robert_barclay_apologie_1776"
tags = ["Documentation", "Docs", "Responsive", "Google analytics", "Table Of Contents"]
features = ["documentation", "menu"]
min_version = "0.60.0"


[params]
    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" #"open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar



# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

[outputs]
    home = ["HTML", "RSS", "Algolia"]

# # Algolia Search configure section
# [outputFormats.Algolia]
#     baseName = "algolia"
#     mediaType = "application/json"
#     isPlainText = true
#     notAlternative = true

# [params.algolia]
#     vars = [
#         "title",
#         "summary",
#         "content",
#         "date",
#         "publishdate",
#         "description",
#         "permalink",
#         "keywords",
#         "lastmod",
#     ]
#     params = [
#         "tags",
#         "categories",
#     ]

