name: Hugo build test
run-name: ${{ github.actor }} testing build with Hugo.
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: switch to HEAD
        run: git checkout HEAD^
      - name: install Hugo
        run: scripts/install_hugo.sh
      - name: build HTML
        run: |
              ./cache/hugo \
                --source ./hugo \
                --baseURL  https://olafradicke.github.io/robert_barclay_apologie_1776 \
                --destination ../docs